### PR TITLE
add prettier

### PR DESCRIPTION
**Pull request by t4sk**
Add auto code formatter (Prettier). On VSCode, this can be triggered on file save.

`npm run lint` to format code

### CODE REVIEW

**Comment by yellowgh0st** [comment]
Looks like there's a test issue. Have you used yarn to add the dependency?
Can you solve that?

**Review by yellowgh0st — CHANGES_REQUESTED** [review]
I'm guessing that the use of yarn might be needed instead of npm.

**Comment by 0xCubed** [comment]
Hi guys, I took some of the work here as I was working on adding some checks to the CI: https://github.com/vetherasset/vaderprotocol-contracts/pull/77

**Comment by yellowgh0st** [comment]
Fixed in 442c83aa8929eed4d753d3a78de98a58294e4026

**Pull request closed without merging**
